-- Create schemas first
CREATE SCHEMA IF NOT EXISTS chat_service;
CREATE SCHEMA IF NOT EXISTS user_service;
CREATE SCHEMA IF NOT EXISTS notification_service;


CREATE TABLE chat_service.chat_messages
(
    id         UUID NOT NULL,
    content    TEXT NOT NULL,
    chat_id    UUID NOT NULL,
    sender_id  UUID NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_chat_messages PRIMARY KEY (id)
);

CREATE TABLE chat_service.chat_participants
(
    user_id             UUID         NOT NULL,
    username            VARCHAR(255) NOT NULL,
    email               VARCHAR(255) NOT NULL,
    profile_picture_url TEXT,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_chat_participants PRIMARY KEY (user_id)
);

CREATE TABLE chat_service.chat_participants_cross_ref
(
    chat_id        UUID NOT NULL,
    participant_id UUID NOT NULL,
    CONSTRAINT pk_chat_participants_cross_ref PRIMARY KEY (chat_id, participant_id)
);

CREATE TABLE chat_service.chats
(
    id         UUID NOT NULL,
    creator_id UUID NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_chats PRIMARY KEY (id)
);

ALTER TABLE chat_service.chat_participants
    ADD CONSTRAINT uc_chat_participants_email UNIQUE (email);

ALTER TABLE chat_service.chat_participants
    ADD CONSTRAINT uc_chat_participants_username UNIQUE (username);

CREATE INDEX idx_chat_message_chat_id_created_at ON chat_service.chat_messages (chat_id, created_at DESC);

CREATE INDEX idx_chat_participant_email ON chat_service.chat_participants (email);

CREATE INDEX idx_chat_participant_username ON chat_service.chat_participants (username);

ALTER TABLE chat_service.chats
    ADD CONSTRAINT FK_CHATS_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES chat_service.chat_participants (user_id);

ALTER TABLE chat_service.chat_messages
    ADD CONSTRAINT FK_CHAT_MESSAGES_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chat_service.chats (id) ON DELETE CASCADE;

ALTER TABLE chat_service.chat_messages
    ADD CONSTRAINT FK_CHAT_MESSAGES_ON_SENDER FOREIGN KEY (sender_id) REFERENCES chat_service.chat_participants (user_id);

ALTER TABLE chat_service.chat_participants_cross_ref
    ADD CONSTRAINT fk_chaparcroref_on_chat_entity FOREIGN KEY (chat_id) REFERENCES chat_service.chats (id);

ALTER TABLE chat_service.chat_participants_cross_ref
    ADD CONSTRAINT fk_chaparcroref_on_chat_participant_entity FOREIGN KEY (participant_id) REFERENCES chat_service.chat_participants (user_id);

CREATE TABLE notification_service.device_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    UUID                                    NOT NULL,
    token      VARCHAR(255)                            NOT NULL,
    platform   VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_device_tokens PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_device_tokens_token ON notification_service.device_tokens (token);

CREATE INDEX idx_device_tokens_user_id ON notification_service.device_tokens (user_id);

CREATE TABLE user_service.email_verification_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(255)                            NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id    UUID                                    NOT NULL,
    used_at    TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_email_verification_tokens PRIMARY KEY (id)
);

CREATE TABLE user_service.password_reset_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(255)                            NOT NULL,
    user_id    UUID                                    NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    used_at    TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_password_reset_tokens PRIMARY KEY (id)
);

CREATE TABLE user_service.refresh_tokens
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      UUID                                    NOT NULL,
    hashed_token VARCHAR(255)                            NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

CREATE TABLE user_service.users
(
    id                 UUID         NOT NULL,
    email              VARCHAR(255) NOT NULL,
    username           VARCHAR(255) NOT NULL,
    hashed_password    VARCHAR(255) NOT NULL,
    has_verified_email BOOLEAN      NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE user_service.email_verification_tokens
    ADD CONSTRAINT uc_email_verification_tokens_token UNIQUE (token);

ALTER TABLE user_service.password_reset_tokens
    ADD CONSTRAINT uc_password_reset_tokens_token UNIQUE (token);

ALTER TABLE user_service.users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE user_service.users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

CREATE INDEX idx_password_reset_token_token ON user_service.password_reset_tokens (token);

CREATE INDEX idx_refresh_tokens_user_id ON user_service.refresh_tokens (user_id);

CREATE INDEX idx_refresh_tokens_user_token ON user_service.refresh_tokens (user_id, hashed_token);

CREATE INDEX idx_users_email ON user_service.users (email);

CREATE INDEX idx_users_username ON user_service.users (username);

ALTER TABLE user_service.email_verification_tokens
    ADD CONSTRAINT FK_EMAIL_VERIFICATION_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES user_service.users (id);

ALTER TABLE user_service.password_reset_tokens
    ADD CONSTRAINT FK_PASSWORD_RESET_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES user_service.users (id);